### ISSUE TITLE
Installation instruction 

### ISSUE THREAD

**Issue by idanblich** [aesanch2/sma#3]
Hi , 
Im new with jenkins ,and whould like to use this plugin.
I tried to find the plugin in the available list with no success.
can you please provide the link to the plugin , if its not there can you please provide the hpi file to the installation.
Tx for your work.
Idan

**Comment by aesanch2** [comment]
Hi @idanblich,

This plugin isn't available in the Jenkins plugin repo yet. I attach the hpi under the releases section.

You can find the most recent one here: https://github.com/aesanch2/sma/releases/tag/v1.1.2
